name: webrtc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  # ant_media_flutter: ^0.0.2
  flutter_webrtc: ^0.9.24
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
